[package]
name = "proto"
version = "0.1.0"
authors = ["Adrien Morel <adrien.morel@me.com>"]

[dependencies]
threadpool = "0.1"
hyper = "0.6"
rustc-serialize = "0.3"
time = "0.1"
postgres = "0.10"
log = "0.3"
env_logger = "0.3"
regex = "0.1"
